# Enterprise Data Trust Score Platform

### Notebook : 02_Generate_Dataset.ipynb

**Author:** Himanshu Kataria

**Purpose:**
Generate a realistic employee dataset for Data Quality Validation and Trust Score Analysis.

In [1]:
print("Generating Enterprise Employee Dataset...")

Generating Enterprise Employee Dataset...

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.3

# Company Information

## Company Name
Nova Retail Pvt. Ltd.

## Industry
Retail & E-Commerce

## Headquarters
Bengaluru, India

## Total Employees (Initial Dataset)
50

## Dataset Version
Version 1.0

In [4]:
departments = [
    "Human Resources",
    "Finance",
    "Sales",
    "Marketing",
    "IT",
    "Operations"
]

print(departments)

['Human Resources', 'Finance', 'Sales', 'Marketing', 'IT', 'Operations']

In [5]:
job_titles = [
    "Data Analyst",
    "HR Executive",
    "Sales Executive",
    "Software Engineer",
    "Marketing Executive",
    "Finance Analyst"
]

print(job_titles)

['Data Analyst', 'HR Executive', 'Sales Executive', 'Software Engineer', 'Marketing Executive', 'Finance Analyst']

In [6]:
cities = [
    "Bengaluru",
    "Mumbai",
    "Delhi",
    "Hyderabad",
    "Pune",
    "Jaipur"
]

print(cities)

['Bengaluru', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune', 'Jaipur']

In [7]:
minimum_salary = 25000
maximum_salary = 120000

print("Minimum Salary :", minimum_salary)
print("Maximum Salary :", maximum_salary)

Minimum Salary : 25000
Maximum Salary : 120000

In [8]:
from faker import Faker

fake = Faker("en_IN")

print(fake.name())

Ekta Choudhury

In [9]:
print(fake.email())

rushil57@example.com

In [10]:
print(fake.phone_number())

+918620166917

In [11]:
print(fake.city())

Mango

In [12]:
import random
from faker import Faker

fake = Faker("en_IN")

In [13]:
departments = [
    "Human Resources",
    "Finance",
    "Sales",
    "Marketing",
    "IT",
    "Operations"
]

job_titles = [
    "HR Executive",
    "Finance Analyst",
    "Sales Executive",
    "Marketing Executive",
    "Software Engineer",
    "Data Analyst"
]

cities = [
    "Bengaluru",
    "Mumbai",
    "Delhi",
    "Hyderabad",
    "Pune",
    "Jaipur"
]

In [14]:
employee_data = []

In [15]:
for employee_id in range(1001,1051):

    employee = {

        "Employee_ID": employee_id,

        "First_Name": fake.first_name(),

        "Last_Name": fake.last_name(),

        "Email": fake.email(),

        "Phone": fake.phone_number(),

        "Department": random.choice(departments),

        "Job_Title": random.choice(job_titles),

        "Salary": random.randint(25000,120000),

        "Joining_Date": fake.date_between(
            start_date="-5y",
            end_date="today"
        ),

        "City": random.choice(cities)

    }

    employee_data.append(employee)

In [16]:
employee_df = pd.DataFrame(employee_data)

In [17]:
employee_df

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,+918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
1,1002,Parth,Mittal,girish35@example.net,+917264456495,Sales,Data Analyst,89661,2026-01-02,Pune
2,1003,Ronith,Khare,triya76@example.org,07100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
3,1004,Aarna,Suresh,hwable@example.com,+913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune
4,1005,Nihal,Dugar,girindra53@example.com,+917113970755,IT,HR Executive,41315,2025-12-28,Delhi
5,1006,Gagan,Mishra,umani@example.org,06037451657,Operations,Marketing Executive,61341,2024-10-13,Hyderabad
6,1007,Warinder,Bhatia,ldani@example.org,01001032878,Human Resources,Sales Executive,97035,2021-11-10,Pune
7,1008,Manthan,Sodhi,matthew07@example.net,6846363459,Marketing,Data Analyst,26775,2023-05-28,Hyderabad
8,1009,Anita,Raja,bajajnisha@example.org,3136049415,Operations,Data Analyst,101561,2022-06-30,Mumbai
9,1010,Advay,Golla,malhotrawriddhish@example.com,04771448033,IT,Sales Executive,63365,2025-08-03,Bengaluru
10,1011,Siddharth,Raghavan,amarasura@example.net,07301381213,Marketing,Software Engineer,94785,2021-10-02,Jaipur
11,1012,Jhalak,Lad,srinivasannitesh@example.com,7470899819,Sales,Software Engineer,65650,2024-06-28,Bengaluru
12,1013,Anay,Bhattacharyya,fpurohit@example.net,+917755465541,Marketing,Software Engineer,65613,2023-04-07,Bengaluru
13,1014,Megha,Aggarwal,rajshravya@example.net,05066071131,Human Resources,Finance Analyst,110426,2023-07-20,Delhi
14,1015,Nihal,Sibal,kde@example.com,+910582336121,Sales,Sales Executive,109883,2022-12-16,Bengaluru
15,1016,Harish,Barman,parekhavni@example.com,8750932791,Sales,Software Engineer,66229,2025-07-26,Pune
16,1017,Anusha,Raju,binabora@example.org,+914584024887,Marketing,Software Engineer,37920,2022-10-23,Mumbai
17,1018,Prisha,Balay,karanharrison@example.net,1745304601,Human Resources,Software Engineer,116627,2023-09-22,Jaipur
18,1019,Xiti,Pathak,handawishi@example.org,2900839100,Finance,Software Engineer,46628,2021-12-02,Jaipur
19,1020,Wridesh,Badal,neha72@example.net,8601374927,Marketing,Sales Executive,72659,2026-01-30,Pune
20,1021,Lajita,Ray,anaybajaj@example.com,08915445195,IT,Finance Analyst,52933,2025-11-06,Pune
21,1022,Ladli,Oak,matthew79@example.com,+911433688538,Marketing,Software Engineer,59147,2023-01-13,Jaipur
22,1023,Yashvi,Pall,kdua@example.net,07502086031,Operations,Marketing Executive,83790,2023-07-20,Delhi
23,1024,Radhika,Agarwal,jedwin@example.net,4692133197,Human Resources,Marketing Executive,110380,2024-10-29,Hyderabad
24,1025,Gautami,Sankar,choudharybhavna@example.net,03275965491,Human Resources,HR Executive,118061,2025-09-12,Delhi
25,1026,Odika,Datta,sankaranaarna@example.net,+916325959429,Operations,Sales Executive,108508,2022-09-18,Jaipur
26,1027,Harshil,Nayar,gabriel13@example.net,05222020020,Operations,HR Executive,82073,2025-09-08,Jaipur
27,1028,Abhiram,Handa,vbhat@example.org,04687944869,Marketing,Software Engineer,41264,2025-07-14,Pune
28,1029,Balendra,Sangha,krishnabumb@example.net,02766179930,Sales,Sales Executive,104895,2023-11-03,Bengaluru
29,1030,Isha,Parmar,pallagaurav@example.org,09177355658,IT,Marketing Executive,64721,2026-04-20,Mumbai
30,1031,Chandran,Dubey,esheth@example.org,01719713254,IT,Software Engineer,95377,2023-02-16,Delhi
31,1032,Janya,Tripathi,falakwason@example.org,03131329776,Operations,Marketing Executive,94855,2025-10-05,Mumbai
32,1033,Gauri,Dixit,upandya@example.com,+913453744514,Marketing,Software Engineer,35968,2024-03-15,Bengaluru
33,1034,Nakul,Doctor,hariwahab@example.com,+915515310790,Marketing,Software Engineer,105766,2024-05-07,Hyderabad
34,1035,Yochana,Morar,aparekh@example.net,09305182584,IT,HR Executive,88605,2025-12-15,Hyderabad
35,1036,Raagini,Sood,advikbedi@example.net,01343824707,Finance,Sales Executive,65120,2025-07-21,Pune
36,1037,Zaitra,Goswami,omisha67@example.org,06802832690,Marketing,Data Analyst,43578,2024-07-30,Jaipur
37,1038,Lila,Jani,andrew21@example.com,+917427780645,Operations,Data Analyst,77378,2024-07-10,Jaipur
38,1039,Jasmit,Cherian,mahalharsh@example.com,+918350662552,IT,Software Engineer,104865,2025-01-05,Jaipur
39,1040,Yauvani,Mand,meeraissac@example.com,03846827635,IT,Finance Analyst,73229,2024-10-05,Delhi
40,1041,Jalsa,Sarma,jagat62@example.org,0288532178,Finance,Data Analyst,27913,2022-05-15,Bengaluru
41,1042,Jack,Rajagopal,chadhareva@example.org,01160780922,IT,HR Executive,60957,2024-10-19,Jaipur
42,1043,Raagini,Rajagopal,rajchasmum@example.org,00969452530,IT,Software Engineer,86754,2024-07-20,Delhi
43,1044,Kashish,Kothari,abalakrishnan@example.net,8427780199,IT,Finance Analyst,93667,2025-09-01,Jaipur
44,1045,Bhavika,Merchant,zilmilbuch@example.com,05575698389,IT,Sales Executive,76295,2024-05-29,Jaipur
45,1046,Qasim,Pandit,victor23@example.com,+911870608611,Human Resources,Software Engineer,115997,2022-11-11,Mumbai
46,1047,Reva,Rau,yashvisarkar@example.com,6338406379,Human Resources,Finance Analyst,105440,2022-11-28,Delhi
47,1048,Ryan,Lall,jairattan@example.org,05889119791,Human Resources,Sales Executive,111181,2026-02-22,Jaipur
48,1049,Upma,Rama,xbir@example.net,+915071112489,Finance,Finance Analyst,59279,2022-06-19,Jaipur
49,1050,Vanya,Sangha,nathan56@example.org,9742890173,Human Resources,Data Analyst,117664,2022-04-01,Delhi

In [18]:
employee_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,+918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
1,1002,Parth,Mittal,girish35@example.net,+917264456495,Sales,Data Analyst,89661,2026-01-02,Pune
2,1003,Ronith,Khare,triya76@example.org,07100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
3,1004,Aarna,Suresh,hwable@example.com,+913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune
4,1005,Nihal,Dugar,girindra53@example.com,+917113970755,IT,HR Executive,41315,2025-12-28,Delhi

In [19]:
employee_df.tail()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
45,1046,Qasim,Pandit,victor23@example.com,+911870608611,Human Resources,Software Engineer,115997,2022-11-11,Mumbai
46,1047,Reva,Rau,yashvisarkar@example.com,6338406379,Human Resources,Finance Analyst,105440,2022-11-28,Delhi
47,1048,Ryan,Lall,jairattan@example.org,05889119791,Human Resources,Sales Executive,111181,2026-02-22,Jaipur
48,1049,Upma,Rama,xbir@example.net,+915071112489,Finance,Finance Analyst,59279,2022-06-19,Jaipur
49,1050,Vanya,Sangha,nathan56@example.org,9742890173,Human Resources,Data Analyst,117664,2022-04-01,Delhi

In [20]:
employee_df.shape

(50, 10)

In [21]:
employee_df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Email', 'Phone',
       'Department', 'Job_Title', 'Salary', 'Joining_Date', 'City'],
      dtype='object')

In [22]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   50 non-null     int64
 1   First_Name    50 non-null     object
 2   Last_Name     50 non-null     object
 3   Email         50 non-null     object
 4   Phone         50 non-null     object
 5   Department    50 non-null     object
 6   Job_Title     50 non-null     object
 7   Salary        50 non-null     int64
 8   Joining_Date  50 non-null     object
 9   City          50 non-null     object
dtypes: int64(2), object(8)
memory usage: 4.0+ KB

In [23]:
employee_df.describe()

       Employee_ID         Salary
count     50.00000      50.000000
mean    1025.50000   78062.140000
std       14.57738   26867.241612
min     1001.00000   26775.000000
25%     1013.25000   61043.500000
50%     1025.50000   77076.500000
75%     1037.75000  104039.000000
max     1050.00000  118061.000000

In [24]:
employee_df.to_csv(
    "../data/raw/employee_data.csv",
    index=False
)

In [25]:
print("Dataset Saved Successfully ✅")

Dataset Saved Successfully ✅

In [26]:
employee_df = pd.read_csv("../data/raw/employee_data.csv")

In [27]:
employee_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune
2,1003,Ronith,Khare,triya76@example.org,7100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi

In [28]:
employee_df.shape

(50, 10)

In [29]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   50 non-null     int64
 1   First_Name    50 non-null     object
 2   Last_Name     50 non-null     object
 3   Email         50 non-null     object
 4   Phone         50 non-null     int64
 5   Department    50 non-null     object
 6   Job_Title     50 non-null     object
 7   Salary        50 non-null     int64
 8   Joining_Date  50 non-null     object
 9   City          50 non-null     object
dtypes: int64(3), object(7)
memory usage: 4.0+ KB

In [30]:
employee_df.dtypes

Employee_ID      int64
First_Name      object
Last_Name       object
Email           object
Phone            int64
Department      object
Job_Title       object
Salary           int64
Joining_Date    object
City            object
dtype: object

In [31]:
employee_df.isnull().sum()

Employee_ID     0
First_Name      0
Last_Name       0
Email           0
Phone           0
Department      0
Job_Title       0
Salary          0
Joining_Date    0
City            0
dtype: int64

In [32]:
employee_df.duplicated().sum()

np.int64(0)

In [33]:
employee_df.nunique()

Employee_ID     50
First_Name      48
Last_Name       48
Email           50
Phone           50
Department       6
Job_Title        6
Salary          50
Joining_Date    49
City             6
dtype: int64

In [34]:
employee_df["Department"].value_counts()

Department
IT                 12
Marketing          11
Human Resources    10
Operations          7
Sales               5
Finance             5
Name: count, dtype: int64

In [35]:
employee_df["City"].value_counts()

City
Jaipur       14
Delhi         9
Pune          8
Bengaluru     8
Mumbai        6
Hyderabad     5
Name: count, dtype: int64

In [36]:
dirty_employee_df = employee_df.copy()

In [37]:
dirty_employee_df.loc[5, "Email"] = None

In [38]:
dirty_employee_df.loc[10, "Salary"] = -5000

In [39]:
dirty_employee_df.loc[15, "Department"] = "Gaming"

In [40]:
dirty_employee_df.loc[20, "Joining_Date"] = "2035-01-01"

In [41]:
dirty_employee_df.loc[25, "Employee_ID"] = 1001

In [42]:
dirty_employee_df.to_csv(
    "../data/processed/dirty_employee_data.csv",
    index=False
)