In [1]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
dirty_df = pd.read_csv("../data/processed/dirty_employee_data.csv")

dirty_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune
2,1003,Ronith,Khare,triya76@example.org,7100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi

In [3]:
dirty_df.shape

(50, 10)

In [4]:
dirty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   50 non-null     int64
 1   First_Name    50 non-null     object
 2   Last_Name     50 non-null     object
 3   Email         49 non-null     object
 4   Phone         50 non-null     int64
 5   Department    50 non-null     object
 6   Job_Title     50 non-null     object
 7   Salary        50 non-null     int64
 8   Joining_Date  50 non-null     object
 9   City          50 non-null     object
dtypes: int64(3), object(7)
memory usage: 4.0+ KB

In [5]:
dirty_df.isnull().sum()

Employee_ID     0
First_Name      0
Last_Name       0
Email           1
Phone           0
Department      0
Job_Title       0
Salary          0
Joining_Date    0
City            0
dtype: int64

In [6]:
dirty_df["Employee_ID"].duplicated().sum()

np.int64(1)

In [7]:
dirty_df[
    (dirty_df["Salary"] < 25000) |
    (dirty_df["Salary"] > 120000)
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
10,1011,Siddharth,Raghavan,amarasura@example.net,7301381213,Marketing,Software Engineer,-5000,2021-10-02,Jaipur

In [8]:
valid_departments = [
    "IT",
    "HR",
    "Finance",
    "Sales",
    "Marketing",
    "Operations"
]

dirty_df[
    ~dirty_df["Department"].isin(valid_departments)
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
2,1003,Ronith,Khare,triya76@example.org,7100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
6,1007,Warinder,Bhatia,ldani@example.org,1001032878,Human Resources,Sales Executive,97035,2021-11-10,Pune
13,1014,Megha,Aggarwal,rajshravya@example.net,5066071131,Human Resources,Finance Analyst,110426,2023-07-20,Delhi
15,1016,Harish,Barman,parekhavni@example.com,8750932791,Gaming,Software Engineer,66229,2025-07-26,Pune
17,1018,Prisha,Balay,karanharrison@example.net,1745304601,Human Resources,Software Engineer,116627,2023-09-22,Jaipur
23,1024,Radhika,Agarwal,jedwin@example.net,4692133197,Human Resources,Marketing Executive,110380,2024-10-29,Hyderabad
24,1025,Gautami,Sankar,choudharybhavna@example.net,3275965491,Human Resources,HR Executive,118061,2025-09-12,Delhi
45,1046,Qasim,Pandit,victor23@example.com,911870608611,Human Resources,Software Engineer,115997,2022-11-11,Mumbai
46,1047,Reva,Rau,yashvisarkar@example.com,6338406379,Human Resources,Finance Analyst,105440,2022-11-28,Delhi
47,1048,Ryan,Lall,jairattan@example.org,5889119791,Human Resources,Sales Executive,111181,2026-02-22,Jaipur
49,1050,Vanya,Sangha,nathan56@example.org,9742890173,Human Resources,Data Analyst,117664,2022-04-01,Delhi

In [9]:
dirty_df["Joining_Date"] = pd.to_datetime(dirty_df["Joining_Date"])

dirty_df[
    dirty_df["Joining_Date"] > pd.Timestamp.today()
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
20,1021,Lajita,Ray,anaybajaj@example.com,8915445195,IT,Finance Analyst,52933,2035-01-01,Pune

In [10]:
clean_df = dirty_df.copy()

clean_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune
2,1003,Ronith,Khare,triya76@example.org,7100054839,Human Resources,Sales Executive,61303,2023-05-27,Bengaluru
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi

In [11]:
clean_df[clean_df["Email"].isnull()]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
5,1006,Gagan,Mishra,NaN,6037451657,Operations,Marketing Executive,61341,2024-10-13,Hyderabad

In [12]:
clean_df["Email"] = clean_df["Email"].fillna("unknown@company.com")

In [13]:
clean_df["Email"].isnull().sum()

np.int64(0)

In [14]:
clean_df[
    clean_df["Employee_ID"].duplicated(keep=False)
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai
25,1001,Odika,Datta,sankaranaarna@example.net,916325959429,Operations,Sales Executive,108508,2022-09-18,Jaipur

In [15]:
clean_df = clean_df.drop_duplicates(
    subset="Employee_ID",
    keep="first"
)

In [16]:
clean_df["Employee_ID"].duplicated().sum()

np.int64(0)

In [17]:
clean_df[
    (clean_df["Salary"] < 25000) |
    (clean_df["Salary"] > 120000)
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
10,1011,Siddharth,Raghavan,amarasura@example.net,7301381213,Marketing,Software Engineer,-5000,2021-10-02,Jaipur

In [18]:
clean_df.loc[
    clean_df["Salary"] < 25000,
    "Salary"
] = 25000

In [19]:
clean_df[
    (clean_df["Salary"] < 25000) |
    (clean_df["Salary"] > 120000)
]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Email, Phone, Department, Job_Title, Salary, Joining_Date, City]
Index: []

In [20]:
clean_df[
    (clean_df["Salary"] < 25000) |
    (clean_df["Salary"] > 120000)
]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Email, Phone, Department, Job_Title, Salary, Joining_Date, City]
Index: []

In [21]:
clean_df.loc[
    ~clean_df["Department"].isin(valid_departments),
    "Department"
] = "Operations"

In [22]:
clean_df[
    ~clean_df["Department"].isin(valid_departments)
]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Email, Phone, Department, Job_Title, Salary, Joining_Date, City]
Index: []

In [23]:
clean_df[
    clean_df["Joining_Date"] > pd.Timestamp.today()
]

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City
20,1021,Lajita,Ray,anaybajaj@example.com,8915445195,IT,Finance Analyst,52933,2035-01-01,Pune

In [24]:
clean_df.loc[
    clean_df["Joining_Date"] > pd.Timestamp.today(),
    "Joining_Date"
] = pd.Timestamp.today().normalize()

In [25]:
clean_df[
    clean_df["Joining_Date"] > pd.Timestamp.today()
]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Email, Phone, Department, Job_Title, Salary, Joining_Date, City]
Index: []

In [26]:
print("Missing Emails:", clean_df["Email"].isnull().sum())

print("Duplicate Employee IDs:",
      clean_df["Employee_ID"].duplicated().sum())

print("Invalid Salary:",
      len(
          clean_df[
              (clean_df["Salary"] < 25000) |
              (clean_df["Salary"] > 120000)
          ]
      ))

print("Invalid Department:",
      len(
          clean_df[
              ~clean_df["Department"].isin(valid_departments)
          ]
      ))

print("Future Joining Date:",
      len(
          clean_df[
              clean_df["Joining_Date"] > pd.Timestamp.today()
          ]
      ))

Missing Emails: 0
Duplicate Employee IDs: 0
Invalid Salary: 0
Invalid Department: 0
Future Joining Date: 0

In [27]:
clean_df.to_csv(
    "../data/processed/clean_employee_data.csv",
    index=False
)

print("Clean Dataset Saved Successfully")

Clean Dataset Saved Successfully

In [28]:
clean_df.shape

(49, 10)