In [1]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
clean_df = pd.read_csv("../data/processed/clean_employee_data.csv")

clean_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City,Trust_Score,Trust_Category
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai,100,Excellent
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune,100,Excellent
2,1003,Ronith,Khare,triya76@example.org,7100054839,Operations,Sales Executive,61303,2023-05-27,Bengaluru,100,Excellent
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune,100,Excellent
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi,100,Excellent

In [3]:
clean_df.shape

(49, 12)

In [4]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     49 non-null     int64
 1   First_Name      49 non-null     object
 2   Last_Name       49 non-null     object
 3   Email           49 non-null     object
 4   Phone           49 non-null     int64
 5   Department      49 non-null     object
 6   Job_Title       49 non-null     object
 7   Salary          49 non-null     int64
 8   Joining_Date    49 non-null     object
 9   City            49 non-null     object
 10  Trust_Score     49 non-null     int64
 11  Trust_Category  49 non-null     object
dtypes: int64(4), object(8)
memory usage: 4.7+ KB

In [5]:
clean_df["Trust_Score"] = 100

In [6]:
clean_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City,Trust_Score,Trust_Category
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai,100,Excellent
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune,100,Excellent
2,1003,Ronith,Khare,triya76@example.org,7100054839,Operations,Sales Executive,61303,2023-05-27,Bengaluru,100,Excellent
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune,100,Excellent
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi,100,Excellent

In [7]:
def calculate_trust_score(row):

    score = 100

    # Missing Email
    if pd.isna(row["Email"]):
        score -= 20

    # Invalid Salary
    if row["Salary"] < 25000 or row["Salary"] > 120000:
        score -= 20

    # Invalid Department
    valid_departments = [
        "IT",
        "HR",
        "Finance",
        "Sales",
        "Marketing",
        "Operations"
    ]

    if row["Department"] not in valid_departments:
        score -= 15

    # Future Joining Date
    joining_date = pd.to_datetime(row["Joining_Date"])

    if joining_date > pd.Timestamp.today():
        score -= 15

    return max(score, 0)

In [8]:
clean_df["Trust_Score"] = clean_df.apply(
    calculate_trust_score,
    axis=1
)

In [9]:
clean_df.head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City,Trust_Score,Trust_Category
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai,100,Excellent
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune,100,Excellent
2,1003,Ronith,Khare,triya76@example.org,7100054839,Operations,Sales Executive,61303,2023-05-27,Bengaluru,100,Excellent
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune,100,Excellent
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi,100,Excellent

In [10]:
clean_df["Trust_Score"].describe()

count     49.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
Name: Trust_Score, dtype: float64

In [11]:
def trust_category(score):
    if score >= 90:
        return "Excellent"
    elif score >= 75:
        return "Good"
    elif score >= 50:
        return "Fair"
    else:
        return "Poor"

clean_df["Trust_Category"] = clean_df["Trust_Score"].apply(trust_category)

In [12]:
clean_df[["Employee_ID", "Trust_Score", "Trust_Category"]].head()

   Employee_ID  Trust_Score Trust_Category
0         1001          100      Excellent
1         1002          100      Excellent
2         1003          100      Excellent
3         1004          100      Excellent
4         1005          100      Excellent

In [13]:
clean_df.to_csv(
    "../data/processed/clean_employee_data.csv",
    index=False
)

In [14]:
pd.read_csv("../data/processed/clean_employee_data.csv").head()

,Employee_ID,First_Name,Last_Name,Email,Phone,Department,Job_Title,Salary,Joining_Date,City,Trust_Score,Trust_Category
0,1001,Joshua,Bhat,dakshdeshmukh@example.com,918432178907,Marketing,HR Executive,76775,2023-01-23,Mumbai,100,Excellent
1,1002,Parth,Mittal,girish35@example.net,917264456495,Sales,Data Analyst,89661,2026-01-02,Pune,100,Excellent
2,1003,Ronith,Khare,triya76@example.org,7100054839,Operations,Sales Executive,61303,2023-05-27,Bengaluru,100,Excellent
3,1004,Aarna,Suresh,hwable@example.com,913347698680,Finance,Marketing Executive,31896,2023-12-10,Pune,100,Excellent
4,1005,Nihal,Dugar,girindra53@example.com,917113970755,IT,HR Executive,41315,2025-12-28,Delhi,100,Excellent